language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip

env:
  global:
    - TWINE_USERNAME=MarkReedZ

script:
  - pip install cibuildwheel==1.4.0
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/*.whl
    fi
